// Command genmigrations writes both dialects' goose migrations from docs/SCHEMA_V2.sql.
//
// That file is the canonical, annotated schema. An identity column is the one construct
// that cannot be spelled the same way on PostgreSQL and SQLite, so the SQLite copy is the
// same statements with one substitution. Generating both from one source is what stops
// them drifting apart.
//
// Run with: make migrations
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const (
	identity = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
	sqliteID = "INTEGER PRIMARY KEY AUTOINCREMENT"

	// The counts the schema is known to hold. They are asserted rather than reported,
	// because a parse that silently loses a table would generate a migration that boots
	// and is missing something.
	wantTables   = 21
	wantIdentity = 13
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "genmigrations:", err)
		os.Exit(1)
	}
}

func run() error {
	root, err := repoRoot()
	if err != nil {
		return err
	}
	src := filepath.Join(root, "docs", "SCHEMA_V2.sql")

	raw, err := os.ReadFile(src)
	if err != nil {
		return err
	}
	stmts := statements(string(raw))

	var tables, indexes, partial int
	for _, s := range stmts {
		switch u := strings.ToUpper(s); {
		case strings.HasPrefix(u, "CREATE TABLE"):
			tables++
		case strings.HasPrefix(u, "CREATE INDEX"), strings.HasPrefix(u, "CREATE UNIQUE INDEX"):
			indexes++
			if strings.Contains(u, " WHERE ") {
				partial++
			}
		}
	}
	ident := 0
	for _, s := range stmts {
		ident += strings.Count(s, identity)
	}

	if tables != wantTables {
		return fmt.Errorf("expected %d tables, parsed %d", wantTables, tables)
	}
	if tables+indexes != len(stmts) {
		return fmt.Errorf("%d statements but %d tables + %d indexes: something parsed as neither",
			len(stmts), tables, indexes)
	}
	if ident != wantIdentity {
		return fmt.Errorf("expected %d identity columns, found %d", wantIdentity, ident)
	}

	base := filepath.Join(root, "store", "migrations")
	if err := emit(filepath.Join(base, "postgres", "00001_init.sql"), stmts, false,
		"-- PostgreSQL. Identity columns are BIGINT GENERATED BY DEFAULT AS IDENTITY."); err != nil {
		return err
	}
	if err := emit(filepath.Join(base, "sqlite", "00001_init.sql"), stmts, true,
		"-- SQLite. Identity columns become INTEGER PRIMARY KEY AUTOINCREMENT. AUTOINCREMENT\n"+
			"-- is required, not cosmetic: a plain INTEGER PRIMARY KEY reuses row ids after a delete."); err != nil {
		return err
	}

	fmt.Printf("generated 2 dialects: %d statements, %d tables, %d indexes (%d partial), %d identity columns\n",
		len(stmts), tables, indexes, partial, ident)
	return nil
}

// repoRoot walks up from the working directory until it finds go.mod, so the tool works
// from anywhere rather than only from the repo root.
func repoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("no go.mod above %q", dir)
		}
		dir = parent
	}
}

// statements strips comments before splitting on semicolons. Several comments in the
// schema contain a semicolon, so splitting first would tear statements in half.
func statements(src string) []string {
	var kept []string
	for _, line := range strings.Split(src, "\n") {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "--") {
			continue
		}
		if i := strings.Index(line, "--"); i >= 0 {
			line = line[:i]
		}
		kept = append(kept, strings.TrimRight(line, " \t"))
	}
	var out []string
	for _, s := range strings.Split(strings.Join(kept, "\n"), ";") {
		if s = strings.TrimSpace(s); s != "" {
			out = append(out, s)
		}
	}
	return out
}

func emit(path string, stmts []string, sqlite bool, header string) error {
	var b strings.Builder
	b.WriteString("-- Generated from docs/SCHEMA_V2.sql. Do not edit by hand.\n")
	b.WriteString("-- Regenerate with: make migrations\n")
	b.WriteString("--\n")
	b.WriteString(header)
	b.WriteString("\n\n-- +goose Up\n\n")

	for _, s := range stmts {
		if sqlite {
			s = strings.ReplaceAll(s, identity, sqliteID)
		}
		b.WriteString("-- +goose StatementBegin\n")
		b.WriteString(s)
		b.WriteString(";\n-- +goose StatementEnd\n\n")
	}

	b.WriteString("-- +goose Down\n")
	b.WriteString("-- +goose StatementBegin\n")
	b.WriteString("-- Refused on purpose. Migrations are append-only after the first boot, and\n")
	b.WriteString("-- SQLite can neither drop a CHECK nor alter a primary key, so a down migration\n")
	b.WriteString("-- cannot honestly reverse 00001.\n")
	b.WriteString("SELECT 1;\n")
	b.WriteString("-- +goose StatementEnd\n")

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(b.String()), 0o644)
}
