#!/usr/bin/env python3
"""Generate both dialects' goose migrations from docs/SCHEMA_V2.sql.

The canonical, annotated schema is docs/SCHEMA_V2.sql. Identity columns are the one
construct that cannot be spelled the same on PostgreSQL and SQLite, so the SQLite copy is
this file with one substitution. Generating both is what stops them drifting apart.

Run with: make migrations
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "docs", "SCHEMA_V2.sql")

IDENTITY = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
SQLITE_ID = "INTEGER PRIMARY KEY AUTOINCREMENT"


def statements(src: str) -> list[str]:
    # Strip comments before splitting: several comments contain a semicolon, and splitting
    # first would tear statements in half.
    kept = []
    for line in src.split("\n"):
        t = line.strip()
        if t == "" or t.startswith("--"):
            continue
        if "--" in line:
            line = line[: line.index("--")]
        kept.append(line.rstrip())
    return [s.strip() for s in "\n".join(kept).split(";") if s.strip()]


def emit(path: str, stmts: list[str], dialect: str, header: str) -> None:
    out = [
        "-- Generated from docs/SCHEMA_V2.sql. Do not edit by hand.",
        "-- Regenerate with: make migrations",
        "--",
        header,
        "",
        "-- +goose Up",
        "",
    ]
    for s in stmts:
        body = s.replace(IDENTITY, SQLITE_ID) if dialect == "sqlite" else s
        out += ["-- +goose StatementBegin", body + ";", "-- +goose StatementEnd", ""]
    out += [
        "-- +goose Down",
        "-- +goose StatementBegin",
        "-- Refused on purpose. Migrations are append-only after the first boot, and",
        "-- SQLite can neither drop a CHECK nor alter a primary key, so a down migration",
        "-- cannot honestly reverse 00001.",
        "SELECT 1;",
        "-- +goose StatementEnd",
    ]
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write("\n".join(out) + "\n")


def main() -> int:
    stmts = statements(open(SRC).read())
    tables = [s for s in stmts if s.upper().startswith("CREATE TABLE")]
    indexes = [s for s in stmts if s.upper().startswith(("CREATE INDEX", "CREATE UNIQUE INDEX"))]

    if len(tables) != 19:
        print(f"expected 19 tables, parsed {len(tables)}", file=sys.stderr)
        return 1
    if len(tables) + len(indexes) != len(stmts):
        print(f"{len(stmts)} statements but {len(tables)} tables + {len(indexes)} indexes: "
              "something parsed as neither", file=sys.stderr)
        return 1
    n_ident = sum(s.count(IDENTITY) for s in stmts)
    if n_ident != 13:
        print(f"expected 13 identity columns, found {n_ident}", file=sys.stderr)
        return 1

    base = os.path.join(ROOT, "store", "migrations")
    emit(os.path.join(base, "postgres", "00001_init.sql"), stmts, "postgres",
         "-- PostgreSQL. Identity columns are BIGINT GENERATED BY DEFAULT AS IDENTITY.")
    emit(os.path.join(base, "sqlite", "00001_init.sql"), stmts, "sqlite",
         "-- SQLite. Identity columns become INTEGER PRIMARY KEY AUTOINCREMENT. AUTOINCREMENT\n"
         "-- is required, not cosmetic: a plain INTEGER PRIMARY KEY reuses row ids after a delete.")

    partial = [s for s in indexes if " WHERE " in s.upper()]
    print(f"generated 2 dialects: {len(stmts)} statements, {len(tables)} tables, "
          f"{len(indexes)} indexes ({len(partial)} partial), {n_ident} identity columns")
    return 0


if __name__ == "__main__":
    sys.exit(main())
