-- Passion V2 schema. PostgreSQL and SQLite.
--
-- Conventions, and why:
--
--   Dates are VARCHAR(10) holding 'YYYY-MM-DD'. SQLite has no native DATE type, and a
--   fixed-width ISO string sorts and compares correctly on both engines. All date
--   arithmetic happens in Go. Timestamps are TIMESTAMP and are always UTC.
--
--   Fixed-width text is VARCHAR(n) with a length CHECK, never CHAR(n). PostgreSQL treats
--   CHAR as bpchar: it blank-pads on write and ignores trailing spaces on comparison, so
--   a Go "" is stored as 36 spaces there and as '' on SQLite. Same bug, two stored values,
--   and a query that matches on one engine and not the other. The CHECK is what actually
--   holds the width, and SQLite cannot add one later.
--
--   Integer primary keys are `BIGINT GENERATED BY DEFAULT AS IDENTITY` below, which is
--   PostgreSQL syntax. SQLite needs `INTEGER PRIMARY KEY AUTOINCREMENT` instead -- this is
--   the ONE construct in this file that cannot be spelled the same on both engines, and
--   GORM emits the correct form per dialect from a single `primaryKey` tag.
--
--   AUTOINCREMENT is required on SQLite, not optional: a plain INTEGER PRIMARY KEY reuses
--   row ids after a delete (tested -- id 1 was handed to a different row), so a deleted
--   session's id can silently come back attached to something else. That is why the log
--   never groups by an integer id: it groups by a family, which is minted once and is
--   never handed out again. Anything holding a bare id would rot.
--
--   Getting this wrong fails differently per engine: PostgreSQL raises a not-null
--   violation, SQLite accepts the insert and writes a NULL primary key.
--
--   Server-created rows use integer keys. The four log tables use UUID text keys, because
--   a phone with no signal has to invent them. Nothing else is ever client-created.
--
--   No soft deletes anywhere. Foreign keys and cascades do the work. SQLite needs
--   _foreign_keys=on in the DSN, on every pooled connection.
--
--   A NULL number means "not asked". Zero is a real value -- 0 kg is bodyweight.
--
--   Ordering columns are plain integers with no unique constraint. SQLite has no
--   deferrable constraints, so a two-row swap cannot be checked mid-statement. Reorders
--   rewrite every sibling in one transaction.


-- ===========================================================================
-- ACCOUNTS
-- ===========================================================================

CREATE TABLE account (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email                VARCHAR(255) NOT NULL,
  password_hash        VARCHAR(255) NOT NULL,
  height_cm            INTEGER,
  ape_index_cm         INTEGER,
  boulder_grade_system VARCHAR(32)  NOT NULL DEFAULT 'font',
  route_grade_system   VARCHAR(32)  NOT NULL DEFAULT 'french',
  max_pull_ups         INTEGER,
  max_hang_kg          NUMERIC(5,2),

  -- "Today" must be the athlete's day, not the server's. Every heatmap, streak and
  -- calendar boundary depends on it.
  time_zone            VARCHAR(64)  NOT NULL DEFAULT 'UTC',

  -- Carried as a JWT claim and compared on every request. Changing a password bumps it,
  -- which is the only way a stateless token can be revoked before it expires.
  token_epoch          INTEGER      NOT NULL DEFAULT 0,
  created_at           TIMESTAMP    NOT NULL,
  updated_at           TIMESTAMP    NOT NULL,
  CONSTRAINT ux_account_email UNIQUE (email)
);
-- Email is folded to lowercase in Go before every read and write. Never left to the
-- database collation.

CREATE TABLE body_measurement (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id BIGINT      NOT NULL REFERENCES account(id) ON DELETE CASCADE,
  taken_on   VARCHAR(10) NOT NULL,
  weight_kg  NUMERIC(5,2),
  CONSTRAINT ck_body_taken_on    CHECK (length(taken_on) = 10),
  CONSTRAINT ux_body_measurement UNIQUE (account_id, taken_on)
);

CREATE TABLE grade_milestone (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id    BIGINT      NOT NULL REFERENCES account(id) ON DELETE CASCADE,
  taken_on      VARCHAR(10) NOT NULL,
  discipline    VARCHAR(16) NOT NULL,
  grade         VARCHAR(32) NOT NULL,
  grade_ordinal INTEGER     NOT NULL,
  CONSTRAINT ck_grade_discipline CHECK (discipline IN ('boulder','route')),
  CONSTRAINT ck_grade_taken_on   CHECK (length(taken_on) = 10),
  CONSTRAINT ux_grade_milestone  UNIQUE (account_id, discipline, taken_on)
);
-- grade_ordinal exists so progression can be sorted and charted. A grade held only as
-- text cannot be ordered in SQL at all.


-- ===========================================================================
-- CONTENT  --  one table for what the app ships and what a user writes
-- ===========================================================================

CREATE TABLE content (
  -- The local key. Every foreign key in this schema points here, and nothing else does.
  -- It is allowed to differ between two installs of the app and it never leaves the
  -- machine.
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- The global key. It is written in the YAML file, and it is the only identity that
  -- crosses a machine boundary. The importer matches a file to a row on this column, so a
  -- file can be renamed, moved between directories, or have its slug changed, and the row
  -- it owns is still the same row. It is never a foreign key target.
  --
  -- The id has to be IN THE FILE. An id minted at import time is lost the moment a tree is
  -- exported and restored into a fresh database, which is what killed the earlier
  -- content_key design. A row created in the app gets its uuid at insert instead.
  --
  -- wger runs this exact split: uuid to match across installs, integer pk for every join.
  uuid           VARCHAR(36)  NOT NULL,

  -- Which family of rows this one belongs to. Read by history, and by nothing else.
  --
  -- A new row's family is its own uuid. A copy inherits the family of the row it came
  -- from, unchanged, for good. So the app's "Pull Up" and your copy of it share a family,
  -- and one progression chart covers both.
  --
  -- Flat, and never followed. Nothing resolves a family value to a row, so there is no
  -- parent chain to walk and none to rot. wger reached the same shape from the other
  -- direction: it had a Variation table, and migration 0037 deleted it for one indexed
  -- UUID column on the row, because a local group row cannot survive a sync.
  family         VARCHAR(36)  NOT NULL,

  kind           VARCHAR(16)  NOT NULL,
  slug           VARCHAR(128) NOT NULL,
  name           VARCHAR(255) NOT NULL,

  -- Which catalog tree owns this row, or NULL when nothing does.
  --
  -- A re-import rewrites the rows whose source_tree matches the tree being imported. A row
  -- with NULL here is skipped and named in the import report. That is what keeps a YAML
  -- file meaningful after its first import, and what stops a boot erasing something typed
  -- in the app.
  --
  -- Editing a file-owned row in the app sets this to NULL, which detaches the row from its
  -- file for good. The file then has no effect and the app says so, both in the import
  -- report and on the row in the library.
  --
  -- A tree NAME, not its path: paths differ between machines. One nullable column instead
  -- of a boolean plus a name, because two columns can disagree and one cannot.
  source_tree    VARCHAR(64),

  -- NULL author means the app ships this row. No account holds it, so no account's
  -- deletion can reach it. There is no ON DELETE SET NULL on this column anywhere in
  -- the schema: that would silently publish a user's private content into the catalog.
  author_id      BIGINT       REFERENCES account(id) ON DELETE CASCADE,

  notes          TEXT         NOT NULL DEFAULT '',
  source         VARCHAR(64)  NOT NULL DEFAULT '',

  -- Set by the importer when a shipped slug leaves the YAML tree. The library hides these;
  -- plans and logs that reference them keep resolving. Two slugs have already been removed
  -- from the tree in the project's history.
  retired_on     VARCHAR(10),

  -- movement rows: how it is performed, which decides the run screen it gets.
  movement_style VARCHAR(32),

  -- TRUE when the numbers are per side. Without it, "1 set of 6, per side" can only be
  -- said in prose, and the player counts 6 when the athlete owes 12.
  per_side       BOOLEAN      NOT NULL DEFAULT FALSE,
  d_sets         INTEGER,
  d_reps         INTEGER,
  d_weight_kg    NUMERIC(6,2),
  d_rep_seconds      INTEGER,
  d_rep_rest_seconds INTEGER,
  d_set_rest_seconds INTEGER,
  d_prep_seconds     INTEGER,
  d_seconds          INTEGER,

  -- block rows
  block_kind     VARCHAR(16),

  -- menu rows: the FEWEST options you must pick, not the most. 0 is legal and means the
  -- menu may be skipped, which is the only place optionality can live -- the alternative
  -- is the word "optional" inside a display name, which nothing can act on.
  pick_count     INTEGER,

  -- session rows
  color          VARCHAR(16)  NOT NULL DEFAULT '',
  needs          VARCHAR(255) NOT NULL DEFAULT '',

  created_at     TIMESTAMP    NOT NULL,
  updated_at     TIMESTAMP    NOT NULL,

  CONSTRAINT ck_content_kind       CHECK (kind IN ('movement','menu','block','session')),
  CONSTRAINT ck_content_block_kind CHECK (block_kind IS NULL
                                          OR block_kind IN ('warmup','main','cooldown')),
  CONSTRAINT ck_content_style       CHECK (movement_style IS NULL
    OR movement_style IN ('climbing','open','reps_and_sets','timed_reps')),

  -- A menu must say how many options to pick, and nothing else may carry a count. "Pick
  -- NULL of these" has no meaning on the run screen, and a count on a block is dead data.
  CONSTRAINT ck_content_pick       CHECK (
       (kind =  'menu' AND pick_count IS NOT NULL AND pick_count >= 0)
    OR (kind <> 'menu' AND pick_count IS NULL)),

  -- A colon separates a namespace from a name in a reference, so a slug holding one would
  -- make "app:thing" ambiguous. LIKE is the only pattern match both engines share.
  CONSTRAINT ck_content_slug       CHECK (slug NOT LIKE '%:%'),

  -- Dates are compared and sorted as text, so a short one sorts wrong for good.
  CONSTRAINT ck_content_retired    CHECK (retired_on IS NULL OR length(retired_on) = 10),

  -- NOT NULL accepts the empty string, on both engines. Without these, one write path
  -- that forgets to set a family inserts '' and nothing complains -- and every row it
  -- touches then shares one family, so they all chart as one movement. The log is frozen,
  -- so there is no repair afterwards.
  CONSTRAINT ck_content_uuid       CHECK (length(uuid) = 36),
  CONSTRAINT ck_content_family     CHECK (length(family) = 36),

  -- The target of the composite foreign keys in content_item, plan_slot and scheduled.
  -- Redundant on its own; it is what lets those tables constrain WHICH KIND they point at.
  CONSTRAINT ux_content_id_kind    UNIQUE (id, kind)
);

-- Two partial unique indexes, not one. All engines treat NULLs in a unique key as
-- distinct, so a single UNIQUE(author_id, kind, slug) would let two shipped rows share a
-- slug. PostgreSQL and SQLite both support the predicate; MySQL does not, which is why
-- MySQL is out of scope.
CREATE UNIQUE INDEX ux_content_shipped ON content (kind, slug)            WHERE author_id IS NULL;
CREATE UNIQUE INDEX ux_content_mine    ON content (author_id, kind, slug) WHERE author_id IS NOT NULL;

-- Scoped to the owner, for the same reason the slug indexes above are. A global unique
-- index here would mean two accounts cannot both add the same published catalog directory:
-- whoever boots first takes the ids and the other account's import fails on every boot,
-- forever. Sharing a tree is the main way a catalog gets distributed, so that is backwards.
--
-- Scoped, it also makes copying a file DO THE RIGHT THING. Copy the app's movements/x.yaml
-- into your own tree unchanged and you get a second row in your own namespace holding the
-- same uuid, so the same family, so one chart. Copy a file WITHIN one tree and forget to
-- change its id, and that still collides -- which is the mistake this exists to catch, and
-- the single most reported failure in every comparable project.
CREATE UNIQUE INDEX ux_content_uuid_shipped ON content (uuid)            WHERE author_id IS NULL;
CREATE UNIQUE INDEX ux_content_uuid_mine    ON content (author_id, uuid) WHERE author_id IS NOT NULL;

-- Not unique, on purpose. Every row in one family carries the same value.
CREATE INDEX ix_content_family ON content (family);

CREATE INDEX ix_content_author ON content (author_id);
CREATE INDEX ix_content_kind   ON content (kind);
CREATE INDEX ix_content_list   ON content (author_id, kind, name);


-- Every edge in the content tree, and the prescribed numbers for that use.
--
-- The numbers live HERE and not on the movement. That is what lets one movement row be
-- referenced by every session that uses it, and it is what wger does for the same reason.
--
-- The kind columns are duplicated from content, but a composite foreign key keeps each
-- one honest, so they cannot disagree. Enumerating the legal pairs makes a cycle
-- structurally impossible -- there is no legal edge from a movement to anything.
CREATE TABLE content_item (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  parent_id        BIGINT      NOT NULL,
  parent_kind      VARCHAR(16) NOT NULL,
  child_id         BIGINT      NOT NULL,
  child_kind       VARCHAR(16) NOT NULL,

  position         INTEGER     NOT NULL,

  sets             INTEGER,
  reps             INTEGER,
  weight_kg        NUMERIC(6,2),
  rep_seconds      INTEGER,
  rep_rest_seconds INTEGER,
  set_rest_seconds INTEGER,
  prep_seconds     INTEGER,
  seconds          INTEGER,
  notes            TEXT        NOT NULL DEFAULT '',

  CONSTRAINT fk_item_parent FOREIGN KEY (parent_id, parent_kind)
    REFERENCES content (id, kind) ON DELETE CASCADE,
  -- Deferrable, not RESTRICT. Deleting an account cascades content and its edges in one
  -- statement, and Postgres checks a RESTRICT row-by-row mid-cascade and refuses, while
  -- SQLite allows it. Same DDL, opposite behaviour. Tested. Deferring the check to commit
  -- makes both engines agree.
  CONSTRAINT fk_item_child  FOREIGN KEY (child_id, child_kind)
    REFERENCES content (id, kind) ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED,

  CONSTRAINT ck_item_pair CHECK (
       (parent_kind = 'session' AND child_kind = 'block')
    OR (parent_kind = 'block'   AND child_kind IN ('movement','menu'))
    OR (parent_kind = 'menu'    AND child_kind = 'movement')
  ),
  CONSTRAINT ck_item_not_self CHECK (parent_id <> child_id),
  CONSTRAINT ck_item_position  CHECK (position >= 0),

  CONSTRAINT ux_item_edge UNIQUE (parent_id, child_id)
);
CREATE INDEX ix_item_parent ON content_item (parent_id, position);
CREATE INDEX ix_item_child  ON content_item (child_id);

-- Per-set planned targets, when the sets differ from each other.
-- A table and not a JSON column, because the editor saves and deletes one set at a time.
CREATE TABLE content_item_set (
  content_item_id BIGINT  NOT NULL REFERENCES content_item(id) ON DELETE CASCADE,
  set_index       INTEGER NOT NULL,
  rep_index       INTEGER NOT NULL DEFAULT 0,
  reps            INTEGER,
  weight_kg       NUMERIC(6,2),
  seconds         INTEGER,
  PRIMARY KEY (content_item_id, set_index, rep_index),
  CONSTRAINT ck_set_index CHECK (set_index >= 1),
  CONSTRAINT ck_rep_index CHECK (rep_index >= 0)
);


-- A movement's OWN per-rep numbers, when its reps are not all the same. The mirror of
-- content_item_set one level up: that table holds what a block asks for, this one holds
-- what the movement is.
--
-- It exists because a movement can BE a ladder. A 3s, then 6s, then 9s hang is not a choice
-- a block makes about a plain hang; it is what the movement is, and its name says so.
-- Without this table such a shape could only be written inside one block, so no library
-- could hold one.
--
-- Other training apps keep their movement library plain and put non-uniform sets in the
-- workout. They can, because they also have a library of named protocols. The equivalent
-- here would be a block inside a block, which ck_item_pair forbids on purpose. See
-- docs/V2_PLAN.md 1.1 row 14.
--
-- Most movements need no row here.
CREATE TABLE content_set (
  content_id BIGINT  NOT NULL REFERENCES content(id) ON DELETE CASCADE,
  set_index  INTEGER NOT NULL,
  rep_index  INTEGER NOT NULL DEFAULT 0,
  reps       INTEGER,
  weight_kg  NUMERIC(6,2),
  seconds    INTEGER,
  PRIMARY KEY (content_id, set_index, rep_index),
  CONSTRAINT ck_content_set_index CHECK (set_index >= 1),
  CONSTRAINT ck_content_rep_index CHECK (rep_index >= 0)
);
-- A ladder lives here too: rungs of 3, 6 and 9 seconds are three rows, not the string
-- "3,6,9" in a column. That way the target and what you actually did are the same shape,
-- so the log can compare them without the app parsing anything.
--
-- rep_index is why the key has three columns. A ladder's rungs are REPS INSIDE ONE SET,
-- not sets, so (item, set) alone cannot hold them. An ordinary set is rep_index 0; a
-- three-rung ladder is set 1 with rep_index 1, 2, 3. This is in migration 001 because
-- SQLite cannot alter a primary key afterwards.

-- A person's own numbers for a movement they do not own.
--
-- The problem it solves: the app ships "Half Crimp Hang" and suggests 20 kg. You use 25.
-- Without this table the only way to record that is to copy the whole movement, which
-- creates a second row, a second identity, and a second history to reconcile. An override
-- creates none of those. The app's row stays the app's row, so a later release improving
-- its notes still reaches you, and your 25 kg still holds.
--
-- NULL means "no opinion about this number", not zero. Only the fields you set apply.
--
-- Resolution order for a number, weakest first:
--   1. the movement row's own d_* default
--   2. this table, for the account running the session
--   3. the content_item override on the slot being run
--   4. what the person enters while running
--
-- Level 3 beats level 2 because a slot is a prescription: a session that ramps 60/70/80%
-- must not collapse into one number. A shipped catalog file therefore must not set an
-- absolute weight_kg on an item; the importer refuses one, because it would silently
-- override this table for every account.
--
-- Keyed by movement_id and not by slug: the importer matches an existing row and UPDATEs
-- it, so an id survives every re-import and every rename. The constant movement_kind with
-- a composite foreign key is what makes "only a movement" declarative rather than a rule
-- in code, and it is the same shape plan_target already uses.
CREATE TABLE movement_pref (
  account_id    BIGINT      NOT NULL REFERENCES account(id) ON DELETE CASCADE,
  movement_id   BIGINT      NOT NULL,
  movement_kind VARCHAR(16) NOT NULL DEFAULT 'movement',

  sets              INTEGER,
  reps              INTEGER,
  weight_kg         NUMERIC(6,2),
  rep_seconds       INTEGER,
  rep_rest_seconds  INTEGER,
  set_rest_seconds  INTEGER,
  prep_seconds      INTEGER,
  seconds           INTEGER,

  created_at    TIMESTAMP   NOT NULL,
  updated_at    TIMESTAMP   NOT NULL,

  PRIMARY KEY (account_id, movement_id),
  CONSTRAINT ck_pref_kind CHECK (movement_kind = 'movement'),
  CONSTRAINT fk_pref_movement FOREIGN KEY (movement_id, movement_kind)
    REFERENCES content (id, kind) ON DELETE CASCADE
);

CREATE TABLE content_media (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content_id BIGINT       NOT NULL REFERENCES content(id) ON DELETE CASCADE,
  url        VARCHAR(512) NOT NULL,
  thumb_url  VARCHAR(512) NOT NULL DEFAULT '',
  position   INTEGER      NOT NULL DEFAULT 0
);
CREATE INDEX ix_media_content ON content_media (content_id);

CREATE TABLE tag (
  id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug VARCHAR(64) NOT NULL,
  name VARCHAR(64) NOT NULL,
  CONSTRAINT ux_tag_slug UNIQUE (slug)
);

CREATE TABLE content_tag (
  content_id BIGINT NOT NULL REFERENCES content(id) ON DELETE CASCADE,
  tag_id     BIGINT NOT NULL REFERENCES tag(id)     ON DELETE CASCADE,
  PRIMARY KEY (content_id, tag_id)
);
CREATE INDEX ix_content_tag_tag ON content_tag (tag_id);


-- ===========================================================================
-- PLANNING
-- ===========================================================================

CREATE TABLE plan (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id BIGINT       NOT NULL REFERENCES account(id) ON DELETE CASCADE,
  name       VARCHAR(255) NOT NULL,
  starts_on  VARCHAR(10)  NOT NULL,
  weeks      INTEGER      NOT NULL,
  goal       VARCHAR(255) NOT NULL DEFAULT '',
  focus      VARCHAR(32)  NOT NULL DEFAULT '',
  notes      TEXT         NOT NULL DEFAULT '',
  goals_json TEXT         NOT NULL DEFAULT '[]',
  created_at TIMESTAMP    NOT NULL,
  updated_at TIMESTAMP    NOT NULL,
  CONSTRAINT ck_plan_weeks     CHECK (weeks >= 1),
  CONSTRAINT ck_plan_starts_on CHECK (length(starts_on) = 10)
);
CREATE INDEX ix_plan_account ON plan (account_id);
-- goals_json holds the before/after/how goals. They are only ever read and written with
-- the plan, never queried across plans, so they do not earn a table.

CREATE TABLE plan_slot (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plan_id      BIGINT      NOT NULL REFERENCES plan(id) ON DELETE CASCADE,
  session_id   BIGINT      NOT NULL,
  session_kind VARCHAR(16) NOT NULL DEFAULT 'session',
  weekday      INTEGER     NOT NULL,
  week         INTEGER     NOT NULL DEFAULT 0,
  CONSTRAINT fk_slot_session FOREIGN KEY (session_id, session_kind)
    REFERENCES content (id, kind) ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT ck_slot_session_kind CHECK (session_kind = 'session'),
  CONSTRAINT ck_slot_weekday CHECK (weekday BETWEEN 1 AND 7),
  CONSTRAINT ck_slot_week    CHECK (week >= 0),
  CONSTRAINT ux_slot UNIQUE (plan_id, week, weekday, session_id)
);
-- week 0 means every week. Not NULL: a nullable column in a unique key is not enforced,
-- because NULLs compare distinct.

-- What a cycle asks of one exercise. This is the Exercise targets page.
CREATE TABLE plan_target (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plan_id       BIGINT      NOT NULL REFERENCES plan(id) ON DELETE CASCADE,
  movement_id   BIGINT      NOT NULL,
  movement_kind VARCHAR(16) NOT NULL DEFAULT 'movement',
  week          INTEGER     NOT NULL DEFAULT 0,
  sets          INTEGER,
  reps          INTEGER,
  weight_kg     NUMERIC(6,2),
  rep_seconds   INTEGER,
  CONSTRAINT fk_target_movement FOREIGN KEY (movement_id, movement_kind)
    REFERENCES content (id, kind) ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT ck_target_movement_kind CHECK (movement_kind = 'movement'),
  CONSTRAINT ck_target_week CHECK (week >= 0),
  CONSTRAINT ux_target UNIQUE (plan_id, movement_id, week)
);
-- week 0 is the whole cycle; 1..n is that week only.
--
-- "Varies by week" is NOT a stored flag. It is true when a week > 0 row exists for that
-- plan and movement. A flag could disagree with the rows; a derived answer cannot.
--
-- A target is per movement per plan, so one row covers that movement wherever it appears
-- in the cycle. That is the intent of the page: "this cycle asks 5x5 of weighted
-- pull-ups", not "5x5 in Tuesday's session only".

CREATE TABLE scheduled (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id   BIGINT      NOT NULL REFERENCES account(id) ON DELETE CASCADE,
  plan_id      BIGINT      REFERENCES plan(id) ON DELETE CASCADE,
  session_id   BIGINT      NOT NULL,
  session_kind VARCHAR(16) NOT NULL DEFAULT 'session',
  on_date      VARCHAR(10) NOT NULL,
  position     INTEGER     NOT NULL DEFAULT 0,
  created_at   TIMESTAMP   NOT NULL,
  CONSTRAINT fk_sched_session FOREIGN KEY (session_id, session_kind)
    REFERENCES content (id, kind) ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT ck_sched_session_kind CHECK (session_kind = 'session'),
  CONSTRAINT ck_sched_on_date      CHECK (length(on_date) = 10)
);
CREATE INDEX ix_sched_account ON scheduled (account_id, on_date);
CREATE INDEX ix_sched_plan    ON scheduled (plan_id);
-- plan_id is nullable because a session can be scheduled by hand with no cycle behind it.
-- No natural key is possible as a result: the same session twice on one day is legal, and
-- position tells them apart. Duplicate prevention is the app's job, not a constraint's.

CREATE TABLE calendar_event (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id BIGINT       NOT NULL REFERENCES account(id) ON DELETE CASCADE,
  plan_id    BIGINT       REFERENCES plan(id) ON DELETE CASCADE,
  title      VARCHAR(128) NOT NULL,
  kind       VARCHAR(32)  NOT NULL,
  from_date  VARCHAR(10)  NOT NULL,
  to_date    VARCHAR(10)  NOT NULL,
  blocks     BOOLEAN      NOT NULL DEFAULT TRUE,
  notes      TEXT         NOT NULL DEFAULT '',
  CONSTRAINT ck_event_kind  CHECK (kind IN ('trip','injury','rest','competition','other')),
  -- ck_event_range compares two strings, so a short date does not just sort wrong, it
  -- passes or fails the range test wrongly. These two checks are what make it mean
  -- anything.
  CONSTRAINT ck_event_from  CHECK (length(from_date) = 10),
  CONSTRAINT ck_event_to    CHECK (length(to_date)   = 10),
  CONSTRAINT ck_event_range CHECK (to_date >= from_date)
);
CREATE INDEX ix_event_account ON calendar_event (account_id, from_date);


-- ===========================================================================
-- PLACES
-- ===========================================================================

CREATE TABLE place (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id BIGINT       NOT NULL REFERENCES account(id) ON DELETE CASCADE,
  kind       VARCHAR(16)  NOT NULL,
  name       VARCHAR(128) NOT NULL,
  location   VARCHAR(128) NOT NULL DEFAULT '',
  board_type VARCHAR(32)  NOT NULL DEFAULT '',
  CONSTRAINT ck_place_kind CHECK (kind IN ('gym','crag','board'))
);
CREATE INDEX ix_place_account ON place (account_id);


-- ===========================================================================
-- THE LOG  --  frozen. reads no content table, ever.
-- ===========================================================================
--
-- UUID keys, because a phone with no signal creates these rows.
-- updated_at on all four, because sync has to know what changed.
--
-- Sync is phone to this server and back, and never device to device. That is why a log row
-- may point at content by the local integer movement_id: both ends share one database. If
-- that ever changes, log_entry needs the content uuid beside movement_family -- family to
-- group, uuid to identify -- and it is a NOT NULL text column, so migration 001 or never.
--
-- Every name shown here is this table's own copy. Drop every content table and the whole
-- of history still renders. That is the rule, and place_name is part of it: reading the
-- venue name live would mean renaming a gym rewrites your history.

CREATE TABLE log (
  -- NOT NULL is spelled out: SQLite allows a NULL in a PRIMARY KEY unless the column is
  -- INTEGER PRIMARY KEY, and this one is not.
  id           VARCHAR(36)  PRIMARY KEY NOT NULL,
  account_id   BIGINT       NOT NULL REFERENCES account(id) ON DELETE CASCADE,
  on_date      VARCHAR(10)  NOT NULL,

  scheduled_id BIGINT       REFERENCES scheduled(id) ON DELETE SET NULL,

  -- Four columns, the same four log_entry carries for a movement, for the same reasons.
  -- session_family is what "times completed" counts, and it is NOT the name: a person's
  -- session called Power and the app's session called Power are two workouts, and counting
  -- them together was the fault this column removes.
  --
  -- Empty when a run had no session behind it -- an open session is not a template, so it
  -- belongs to no family and is counted by nothing.
  session_id     BIGINT       REFERENCES content(id) ON DELETE SET NULL,
  session_family VARCHAR(36)  NOT NULL DEFAULT '',
  session_slug   VARCHAR(128) NOT NULL DEFAULT '',
  session_name   VARCHAR(255) NOT NULL DEFAULT '',
  color        VARCHAR(16)  NOT NULL DEFAULT '',

  place_id     BIGINT       REFERENCES place(id) ON DELETE SET NULL,
  place_name   VARCHAR(128) NOT NULL DEFAULT '',
  place_kind   VARCHAR(16)  NOT NULL DEFAULT '',

  state        VARCHAR(16)  NOT NULL,
  started_at   TIMESTAMP,
  ended_at     TIMESTAMP,

  sleep        INTEGER,
  energy       INTEGER,
  rpe          INTEGER,
  focus        VARCHAR(32)  NOT NULL DEFAULT '',
  setting      VARCHAR(16)  NOT NULL DEFAULT '',

  went_well    TEXT         NOT NULL DEFAULT '',
  next_focus   TEXT         NOT NULL DEFAULT '',
  notes        TEXT         NOT NULL DEFAULT '',

  created_at   TIMESTAMP    NOT NULL,
  updated_at   TIMESTAMP    NOT NULL,

  CONSTRAINT ck_log_state CHECK (state IN ('draft','active','done','abandoned')),

  -- Every date index and every history sort compares this as text, so a date written
  -- 2026-9-7 instead of 2026-09-07 sorts before every other September date, for good.
  CONSTRAINT ck_log_on_date CHECK (length(on_date) = 10),

  -- Either a real family or nothing. See ck_content_family: NOT NULL alone lets a short
  -- value through, and a short value silently joins every other short value into one count.
  CONSTRAINT ck_log_session_family CHECK (session_family = '' OR length(session_family) = 36)
);
CREATE INDEX ix_log_account ON log (account_id, on_date);
CREATE INDEX ix_log_session ON log (session_id);
CREATE INDEX ix_log_sync    ON log (account_id, updated_at);
CREATE INDEX ix_log_state   ON log (account_id, state);
-- "how many times have I done this session" -- the mirror of ix_entry_movement one level
-- down. Partial, because an open session has no family and would otherwise fill the index
-- with one repeated empty value.
CREATE INDEX ix_log_family  ON log (session_family, account_id) WHERE session_family <> '';
-- draft is a manual entry still being typed in. Hidden from history until saved.
-- A log with no entries is a journal entry. Not a second table.

CREATE TABLE log_entry (
  -- NOT NULL is spelled out for the reason given on log.id.
  id            VARCHAR(36)  PRIMARY KEY NOT NULL,
  log_id        VARCHAR(36)  NOT NULL REFERENCES log(id) ON DELETE CASCADE,

  position      INTEGER      NOT NULL,
  block_name    VARCHAR(255) NOT NULL DEFAULT '',
  block_kind    VARCHAR(16)  NOT NULL DEFAULT '',

  -- Four columns, four jobs.
  --
  --   movement_id      the row that was run. Goes NULL if that row is deleted outright.
  --   movement_family  the identity history groups by. Text, so it survives that delete.
  --   movement_slug    what the file called it that day.
  --   movement_name    what was on screen that day.
  --
  -- The last two are why the whole of history renders with every content table dropped.
  -- This mirrors log.session_id / session_slug / session_name one level up.
  --
  -- History groups on the family and NOT on the slug. Two reasons. A slug can be taken by
  -- two unrelated movements -- yours and the app's -- and grouping on it silently merges
  -- them into one chart. And a rename would have to rewrite these rows to keep a chart
  -- whole, which is a destructive write against history; the family never changes, so
  -- there is nothing to rewrite.
  movement_id     BIGINT       REFERENCES content(id) ON DELETE SET NULL,
  movement_family VARCHAR(36)  NOT NULL,
  movement_slug   VARCHAR(128) NOT NULL,
  movement_name   VARCHAR(255) NOT NULL,

  -- How the movement was performed. Frozen, because changing a movement's style later
  -- must not change how an old run is drawn.
  movement_style VARCHAR(32) NOT NULL DEFAULT '',

  -- what was asked of you that day
  t_sets        INTEGER,
  t_reps        INTEGER,
  t_weight_kg   NUMERIC(6,2),
  t_rep_seconds      INTEGER,
  t_rep_rest_seconds INTEGER,
  t_set_rest_seconds INTEGER,
  t_prep_seconds     INTEGER,
  t_seconds          INTEGER,

  -- what happened
  state           VARCHAR(16) NOT NULL DEFAULT 'pending',
  elapsed_seconds INTEGER     NOT NULL DEFAULT 0,
  set_mode        VARCHAR(16) NOT NULL DEFAULT 'simple',
  climb_kind      VARCHAR(32) NOT NULL DEFAULT '',
  climb_subtype   VARCHAR(32) NOT NULL DEFAULT '',
  notes           TEXT        NOT NULL DEFAULT '',

  created_at    TIMESTAMP    NOT NULL,
  updated_at    TIMESTAMP    NOT NULL,

  CONSTRAINT ck_entry_state    CHECK (state IN ('pending','done','skipped')),
  CONSTRAINT ck_entry_set_mode CHECK (set_mode IN ('simple','per_set')),

  -- See ck_content_family. A manual entry with no library movement behind it gets its own
  -- fresh family, so it is a singleton and charts alone. Never the empty string, which
  -- would make every such entry one movement.
  CONSTRAINT ck_entry_family   CHECK (length(movement_family) = 36)
);
-- The progression query on the run screen -- "the last five times you did this" -- reads
-- this index by its leading column, then joins log by its primary key for the account and
-- the date. The join is what the removed frozen columns used to avoid, and it costs nothing
-- here: one account holds a few hundred logs.
-- Not bounded by account: log_entry no longer carries account_id, so a query for a shipped
-- movement reads every account's entries for that family and the join to log throws all but
-- yours away. Correct, and the work grows with the number of accounts rather than with your
-- own history. Irrelevant at any size this app will see; written down so it is not met
-- later as a mystery.
CREATE INDEX ix_entry_movement ON log_entry (movement_family, log_id);
CREATE INDEX ix_entry_log      ON log_entry (log_id, position);

-- One set: what was asked of it, and what you did. Both on the row, so an open session
-- with per-set planning needs nothing extra.
CREATE TABLE log_set (
  -- NOT NULL is spelled out for the reason given on log.id, and it matters most here:
  -- these are the rows a phone invents offline. Tested on SQLite -- two inserts with a
  -- NULL id both succeed, leaving two rows nothing can tell apart.
  id              VARCHAR(36) PRIMARY KEY NOT NULL,
  log_entry_id    VARCHAR(36) NOT NULL REFERENCES log_entry(id) ON DELETE CASCADE,
  set_index       INTEGER  NOT NULL,
  rep_index       INTEGER  NOT NULL DEFAULT 0,
  target_reps     INTEGER,
  target_weight_kg NUMERIC(6,2),
  target_seconds  INTEGER,
  reps            INTEGER,
  weight_kg       NUMERIC(6,2),
  seconds         INTEGER,
  updated_at      TIMESTAMP NOT NULL,
  CONSTRAINT ck_log_set_index CHECK (set_index >= 1),
  CONSTRAINT ck_log_rep_index CHECK (rep_index >= 0),
  CONSTRAINT ux_log_set UNIQUE (log_entry_id, set_index, rep_index)
);

CREATE TABLE log_climb (
  -- NOT NULL is spelled out for the reason given on log_set.id.
  id           VARCHAR(36) PRIMARY KEY NOT NULL,
  log_entry_id VARCHAR(36) NOT NULL REFERENCES log_entry(id) ON DELETE CASCADE,
  position     INTEGER     NOT NULL DEFAULT 0,
  kind         VARCHAR(16) NOT NULL,
  setting      VARCHAR(16) NOT NULL DEFAULT '',
  subtype      VARCHAR(32) NOT NULL DEFAULT '',
  grade        VARCHAR(32) NOT NULL DEFAULT '',
  grade_ordinal INTEGER,
  style        VARCHAR(32) NOT NULL DEFAULT '',
  rope_style   VARCHAR(32) NOT NULL DEFAULT '',
  attempts     INTEGER     NOT NULL DEFAULT 0,
  sent         BOOLEAN     NOT NULL DEFAULT FALSE,
  seconds      INTEGER     NOT NULL DEFAULT 0,
  stars        INTEGER     NOT NULL DEFAULT 0,
  focus        TEXT        NOT NULL DEFAULT '',
  thoughts     TEXT        NOT NULL DEFAULT '',
  updated_at   TIMESTAMP   NOT NULL,
  CONSTRAINT ck_climb_kind  CHECK (kind IN ('boulder','sport','trad')),
  CONSTRAINT ck_climb_stars CHECK (stars BETWEEN 0 AND 3)
);
CREATE INDEX ix_climb_entry ON log_climb (log_entry_id, position);
-- grade_ordinal is what makes a pyramid sortable. Nullable, because an ARC lap or a
-- traverse has no grade.
--
-- Climbing is the one kind with no per-set target. There is no "asked 4x3" for
-- bouldering. Its target is the whole step -- log_entry.t_seconds for time on the wall,
-- or t_reps for a problem count -- and these tick rows are the record of what happened.


-- ===========================================================================
-- WHERE A NUMBER COMES FROM
-- ===========================================================================
--
-- Starting a run, for one exercise in one block of one session, in a cycle.
-- First match wins. NULL at a level means "not set here" and falls through.
--
--   1. content_item_set        this set specifically, if the block plans per set
--   2. plan_target week = N    what this cycle asks in week N
--   3. plan_target week = 0    what this cycle asks throughout
--   4. content_item            what the block asks
--   5. movement_pref           your own number for this movement
--   6. content.d_*             the movement's default
--
-- Whatever wins is copied into log_entry.t_* (and log_set.target_*) at the moment the
-- run is created, and is never recomputed. History shows what was asked, forever.
--
-- Alongside it, and never stored as a target, the run screen shows what you last did:
--
--   WITH last5 AS (
--     SELECT e.id, l.on_date
--     FROM   log_entry e
--     JOIN   log l ON l.id = e.log_id
--     WHERE  e.movement_family = :family
--       AND  l.account_id = :me
--       AND  e.state = 'done'
--     ORDER BY l.on_date DESC, e.id DESC
--     LIMIT  5)
--   SELECT last5.on_date, e.t_reps, s.reps, s.weight_kg
--   FROM   last5
--   JOIN   log_entry e ON e.id = last5.id
--   LEFT JOIN log_set s ON s.log_entry_id = e.id
--   ORDER BY last5.on_date DESC, s.set_index;
--
-- Three things the obvious spelling gets wrong, all found in review:
--
--   The LIMIT has to be on the ENTRIES. Joining log_set first fans one entry out to one row
--   per set, so LIMIT 5 on the joined rows returns five sets of one session, not five
--   sessions.
--   state = 'done' is required. ck_entry_state permits pending and skipped, so a hang you
--   skipped last week would come back as what you last did.
--   on_date needs a tiebreaker. Two logs on one day order arbitrarily without one.
--
-- Read from ix_entry_movement by its leading column, then log by primary key. Touches no
-- content table, so the whole of history answers with every content row deleted.


-- ===========================================================================
-- EDITING
-- ===========================================================================
--
-- Three cases, three answers. None of them makes a hidden copy.
--
-- 1. A row you own that came from a file. Edited IN PLACE: same id, same slug, and
--    source_tree set to NULL. The NULL is what stops the next re-import overwriting the
--    edit, and it detaches the row from its file for good. Nothing about your history
--    changes, because the slug did not move.
--
--    The import report names every row it skipped this way, and the library badges them.
--    Without that, a person edits the YAML file, restarts, sees no change, and is told
--    nothing -- and this project's owner hand-edits those files as his main way of working.
--
-- 2. Only the numbers on a movement the app ships. That is movement_pref, not an edit.
--    No new row, no new identity, nothing to reconcile later.
--
-- 3. The structure of something the app ships. That is an explicit "copy to my content"
--    action in the UI, never an implicit one. The copy gets a NEW uuid and INHERITS THE
--    FAMILY, which is what holds your history together across it.
--
--    Copying something the APP ships also keeps the slug, because your names and the app's
--    live in separate unique indexes. Copying something YOU ALREADY OWN cannot: same
--    author, same kind, same slug is refused by ux_content_mine, so the UI must rename.
--    That is the case where the family earns its keep most plainly -- the renamed copy
--    still charts with the row it came from.
--
--    A copy never keeps the original's uuid. Every comparable project that allowed that
--    lost a row to it -- Anki, Logseq, Grafana, Pulumi and Argo CD all document the same
--    failure, where two things sharing one id read as one thing in two states.
--
--    A copy takes the thing and its structure, and stops before the movements:
--
--      copy a session  ->  new session row, new block rows, new content_item edges.
--                          the edges still point at the SAME movement rows.
--      copy a block    ->  new block row and its edges. same movements.
--      copy a movement ->  one new row. media copied.
--
--    Consequence worth saying in the copy dialog: your YAML files still say app:<slug>,
--    so a session you run from a file keeps using the app's row. There is no fallback by
--    design, so nothing silently switches to the copy.
--
-- What is NOT here, and why:
--
--   No replaced_by pointer. wger ships one: upstream publishes "this exercise is gone, use
--   that one", and the importer moves the user's log rows onto the replacement inside a
--   transaction. It needs a guaranteed import order and a fallback for a missing target,
--   and wger gets both wrong -- its own test records the result, which is that a user's
--   logs are deleted.
--
--   We drop a shipped movement about once a year, and retired_on already keeps its history
--   working: the row stays, so the old chart keeps rendering. What retired_on does NOT do
--   is join the old chart to the new movement's, and neither does the family on its own --
--   a replacement is a new file with a new id, so its family is its own.
--
--   Joining them is one line, written by hand in the replacement file:
--
--     # movements/hanging_leg_raises.yaml -- replaces hanging_knee_raises
--     id:     <new>
--     family: <the retired movement's id>
--
--   A person doing that deliberately, in a file, in a commit, is worth more than an
--   automatic write against finished history.
--
--   No forked_from_id, and no parent pointer of any kind. The family is flat. A copy and
--   the row it came from are found by (kind, slug) across the two unique indexes, and
--   "reset to the app's version" is deleting your copy.
--
-- Renaming needs no mechanism at all. The importer matches a file to a row by its uuid, so
-- renaming the file, moving it between directories, or changing its slug all land on the
-- same row and update it in place. Nothing is written to the log, because the family did
-- not move. What a rename still costs is the refs: another file naming the old slug now
-- names nothing, and the importer must say which files broke, in the same commit.


-- ===========================================================================
-- WHAT GORM CANNOT EXPRESS
-- ===========================================================================
--
-- AutoMigrate handles the tables, columns, plain indexes, and the partial unique indexes
-- via `uniqueIndex:...,where:...` -- verified: the sqlite and postgres drivers both emit
-- the predicate. The following need explicit statements beside it, identical on both
-- engines:
--
--   1. The six composite foreign keys into content (id, kind): content_item x2, plan_slot,
--      plan_target, scheduled, movement_pref. GORM has no struct tag for a multi-column
--      reference. log_entry.movement_id is a plain single-column FK and is not one of them.
--   2. UNIQUE (id, kind) on content, since it exists only to be a foreign key target.
--   3. The partial unique indexes on uuid, and ix_log_family, which carry a WHERE clause
--      GORM's uniqueIndex tag can express but a plain index tag cannot.
--
-- SQLite cannot add a CHECK to an existing table, so every CHECK above has to be present
-- when the table is first created. That makes the initial migration a create, never an
-- alter, and it means these statements run in order at first boot.
