-- Passion V2 schema. PostgreSQL and SQLite.
--
-- Conventions, and why:
--
--   Dates are VARCHAR(10) holding 'YYYY-MM-DD'. SQLite has no native DATE type, and a
--   fixed-width ISO string sorts and compares correctly on both engines. All date
--   arithmetic happens in Go. Timestamps are TIMESTAMP and are always UTC.
--
--   Integer primary keys are `BIGINT GENERATED BY DEFAULT AS IDENTITY` below, which is
--   PostgreSQL syntax. SQLite needs `INTEGER PRIMARY KEY AUTOINCREMENT` instead -- this is
--   the ONE construct in this file that cannot be spelled the same on both engines, and
--   GORM emits the correct form per dialect from a single `primaryKey` tag.
--
--   AUTOINCREMENT is required on SQLite, not optional: a plain INTEGER PRIMARY KEY reuses
--   row ids after a delete (tested -- id 1 was handed to a different row), so a deleted
--   session's id can silently come back attached to something else. The log stores slugs
--   rather than ids for exactly this reason, but anything holding a bare id would rot.
--
--   Getting this wrong fails differently per engine: PostgreSQL raises a not-null
--   violation, SQLite accepts the insert and writes a NULL primary key.
--
--   Server-created rows use integer keys. The four log tables use UUID text keys, because
--   a phone with no signal has to invent them. Nothing else is ever client-created.
--
--   No soft deletes anywhere. Foreign keys and cascades do the work. SQLite needs
--   _foreign_keys=on in the DSN, on every pooled connection.
--
--   A NULL number means "not asked". Zero is a real value -- 0 kg is bodyweight.
--
--   Ordering columns are plain integers with no unique constraint. SQLite has no
--   deferrable constraints, so a two-row swap cannot be checked mid-statement. Reorders
--   rewrite every sibling in one transaction.


-- ===========================================================================
-- ACCOUNTS
-- ===========================================================================

CREATE TABLE account (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email                VARCHAR(255) NOT NULL,
  password_hash        VARCHAR(255) NOT NULL,
  height_cm            INTEGER,
  ape_index_cm         INTEGER,
  boulder_grade_system VARCHAR(32)  NOT NULL DEFAULT 'font',
  route_grade_system   VARCHAR(32)  NOT NULL DEFAULT 'french',
  max_pull_ups         INTEGER,
  max_hang_kg          NUMERIC(5,2),

  -- "Today" must be the athlete's day, not the server's. Every heatmap, streak and
  -- calendar boundary depends on it.
  time_zone            VARCHAR(64)  NOT NULL DEFAULT 'UTC',

  -- Carried as a JWT claim and compared on every request. Changing a password bumps it,
  -- which is the only way a stateless token can be revoked before it expires.
  token_epoch          INTEGER      NOT NULL DEFAULT 0,
  created_at           TIMESTAMP    NOT NULL,
  updated_at           TIMESTAMP    NOT NULL,
  CONSTRAINT ux_account_email UNIQUE (email)
);
-- Email is folded to lowercase in Go before every read and write. Never left to the
-- database collation.

CREATE TABLE body_measurement (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id BIGINT      NOT NULL REFERENCES account(id) ON DELETE CASCADE,
  taken_on   VARCHAR(10) NOT NULL,
  weight_kg  NUMERIC(5,2),
  CONSTRAINT ux_body_measurement UNIQUE (account_id, taken_on)
);

CREATE TABLE grade_milestone (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id    BIGINT      NOT NULL REFERENCES account(id) ON DELETE CASCADE,
  taken_on      VARCHAR(10) NOT NULL,
  discipline    VARCHAR(16) NOT NULL,
  grade         VARCHAR(32) NOT NULL,
  grade_ordinal INTEGER     NOT NULL,
  CONSTRAINT ck_grade_discipline CHECK (discipline IN ('boulder','route')),
  CONSTRAINT ux_grade_milestone  UNIQUE (account_id, discipline, taken_on)
);
-- grade_ordinal exists so progression can be sorted and charted. A grade held only as
-- text cannot be ordered in SQL at all.


-- ===========================================================================
-- CONTENT  --  one table for what the app ships and what a user writes
-- ===========================================================================

CREATE TABLE content (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind           VARCHAR(16)  NOT NULL,
  slug           VARCHAR(128) NOT NULL,
  name           VARCHAR(255) NOT NULL,

  -- What a finished run points at. DELIBERATELY NOT UNIQUE: a fork inherits its parent's
  -- value, which is the whole mechanism -- it is what holds one progression together across
  -- an edit. Never add UNIQUE here; that would break forking outright. Not called "uuid"
  -- for exactly that reason, because someone reading "uuid" eventually adds the constraint.
  --
  -- Minted at random on insert and never written into a YAML file. Safe because content and
  -- log live in the same database file and are destroyed together. The one way to break it
  -- is an engine move done by re-running the importer instead of copying every table, which
  -- would mint fresh keys under old log rows. That is a runbook rule, not a schema problem.
  content_key    CHAR(36)     NOT NULL,

  -- Which catalog tree owns this row, or NULL when a person made it in the app (including
  -- every fork). A re-import rewrites exactly the rows whose source_tree matches the tree
  -- being imported, and touches nothing else. That is what keeps a YAML file meaningful
  -- after its first import, and what stops a boot erasing something you typed.
  --
  -- A tree NAME, not its path: paths differ between machines. One nullable column instead
  -- of a boolean plus a name, because two columns can disagree and one cannot.
  source_tree    VARCHAR(64),

  -- NULL author means the app ships this row. No account holds it, so no account's
  -- deletion can reach it. There is no ON DELETE SET NULL on this column anywhere in
  -- the schema: that would silently publish a user's private content into the catalog.
  author_id      BIGINT       REFERENCES account(id) ON DELETE CASCADE,

  -- Provenance of a fork. A fork KEEPS THE ORIGINAL SLUG -- the log's only link back to
  -- a movement is the slug, so changing it on fork would split a user's history in two.
  -- Legal because the unique keys below are per author.
  forked_from_id BIGINT,

  notes          TEXT         NOT NULL DEFAULT '',
  source         VARCHAR(64)  NOT NULL DEFAULT '',

  -- Set by the importer when a shipped slug leaves the YAML tree. The library hides these;
  -- plans and logs that reference them keep resolving. Two slugs have already been removed
  -- from the tree in the project's history.
  retired_on     VARCHAR(10),

  -- movement rows
  movement_kind  VARCHAR(32),

  -- TRUE when the numbers are per side. Without it, "1 set of 6, per side" can only be
  -- said in prose, and the player counts 6 when the athlete owes 12.
  per_side       BOOLEAN      NOT NULL DEFAULT FALSE,
  d_sets         INTEGER,
  d_reps         INTEGER,
  d_weight_kg    NUMERIC(6,2),
  d_rep_seconds      INTEGER,
  d_rep_rest_seconds INTEGER,
  d_set_rest_seconds INTEGER,
  d_prep_seconds     INTEGER,
  d_seconds          INTEGER,

  -- block rows
  block_kind     VARCHAR(16),

  -- menu rows: how many of its options you pick
  pick_count     INTEGER,

  -- session rows
  color          VARCHAR(16)  NOT NULL DEFAULT '',
  needs          VARCHAR(255) NOT NULL DEFAULT '',

  created_at     TIMESTAMP    NOT NULL,
  updated_at     TIMESTAMP    NOT NULL,

  CONSTRAINT ck_content_kind       CHECK (kind IN ('movement','menu','block','session')),
  CONSTRAINT ck_content_block_kind CHECK (block_kind IS NULL
                                          OR block_kind IN ('warmup','main','cooldown')),
  CONSTRAINT ck_content_pick       CHECK (pick_count IS NULL OR pick_count >= 1),
  CONSTRAINT ck_content_not_self   CHECK (forked_from_id IS NULL OR forked_from_id <> id),

  -- Composite, so a fork can only descend from its own kind. RESTRICT and never SET NULL:
  -- a SET NULL on a composite key nulls EVERY column in it, including kind NOT NULL, which
  -- makes any forked-from row undeletable. Tested on both engines.
  CONSTRAINT fk_content_forked FOREIGN KEY (forked_from_id, kind)
    REFERENCES content (id, kind) ON DELETE RESTRICT,

  -- The target of the composite foreign keys in content_item, plan_slot and scheduled.
  -- Redundant on its own; it is what lets those tables constrain WHICH KIND they point at.
  CONSTRAINT ux_content_id_kind    UNIQUE (id, kind)
);

-- Two partial unique indexes, not one. All engines treat NULLs in a unique key as
-- distinct, so a single UNIQUE(author_id, kind, slug) would let two shipped rows share a
-- slug. PostgreSQL and SQLite both support the predicate; MySQL does not, which is why
-- MySQL is out of scope.
CREATE UNIQUE INDEX ux_content_shipped ON content (kind, slug)            WHERE author_id IS NULL;
CREATE UNIQUE INDEX ux_content_mine    ON content (author_id, kind, slug) WHERE author_id IS NOT NULL;

CREATE INDEX ix_content_author ON content (author_id);
CREATE INDEX ix_content_kind   ON content (kind);
CREATE INDEX ix_content_forked ON content (forked_from_id);
CREATE INDEX ix_content_list   ON content (author_id, kind, name);


-- Every edge in the content tree, and the prescribed numbers for that use.
--
-- The numbers live HERE and not on the movement. That is what lets one movement row be
-- referenced by every session that uses it, and it is what wger does for the same reason.
--
-- The kind columns are duplicated from content, but a composite foreign key keeps each
-- one honest, so they cannot disagree. Enumerating the legal pairs makes a cycle
-- structurally impossible -- there is no legal edge from a movement to anything.
CREATE TABLE content_item (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  parent_id        BIGINT      NOT NULL,
  parent_kind      VARCHAR(16) NOT NULL,
  child_id         BIGINT      NOT NULL,
  child_kind       VARCHAR(16) NOT NULL,

  position         INTEGER     NOT NULL,

  sets             INTEGER,
  reps             INTEGER,
  weight_kg        NUMERIC(6,2),
  rep_seconds      INTEGER,
  rep_rest_seconds INTEGER,
  set_rest_seconds INTEGER,
  prep_seconds     INTEGER,
  seconds          INTEGER,
  notes            TEXT        NOT NULL DEFAULT '',

  CONSTRAINT fk_item_parent FOREIGN KEY (parent_id, parent_kind)
    REFERENCES content (id, kind) ON DELETE CASCADE,
  -- Deferrable, not RESTRICT. Deleting an account cascades content and its edges in one
  -- statement, and Postgres checks a RESTRICT row-by-row mid-cascade and refuses, while
  -- SQLite allows it. Same DDL, opposite behaviour. Tested. Deferring the check to commit
  -- makes both engines agree.
  CONSTRAINT fk_item_child  FOREIGN KEY (child_id, child_kind)
    REFERENCES content (id, kind) ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED,

  CONSTRAINT ck_item_pair CHECK (
       (parent_kind = 'session' AND child_kind = 'block')
    OR (parent_kind = 'block'   AND child_kind IN ('movement','menu'))
    OR (parent_kind = 'menu'    AND child_kind = 'movement')
  ),
  CONSTRAINT ck_item_not_self CHECK (parent_id <> child_id),

  CONSTRAINT ux_item_edge UNIQUE (parent_id, child_id)
);
CREATE INDEX ix_item_parent ON content_item (parent_id, position);
CREATE INDEX ix_item_child  ON content_item (child_id);

-- Per-set planned targets, when the sets differ from each other.
-- A table and not a JSON column, because the editor saves and deletes one set at a time.
CREATE TABLE content_item_set (
  content_item_id BIGINT  NOT NULL REFERENCES content_item(id) ON DELETE CASCADE,
  set_index       INTEGER NOT NULL,
  rep_index       INTEGER NOT NULL DEFAULT 0,
  reps            INTEGER,
  weight_kg       NUMERIC(6,2),
  seconds         INTEGER,
  PRIMARY KEY (content_item_id, set_index, rep_index),
  CONSTRAINT ck_set_index CHECK (set_index >= 1),
  CONSTRAINT ck_rep_index CHECK (rep_index >= 0)
);


-- A movement's OWN per-rep numbers, when its reps are not all the same. The mirror of
-- content_item_set one level up: that table holds what a block asks for, this one holds
-- what the movement is.
--
-- It exists because a movement can BE a ladder. A 3s, then 6s, then 9s hang is not a choice
-- a block makes about a plain hang; it is what the movement is, and its name says so.
-- Without this table such a shape could only be written inside one block, so no library
-- could hold one.
--
-- Other training apps keep their movement library plain and put non-uniform sets in the
-- workout. They can, because they also have a library of named protocols. The equivalent
-- here would be a block inside a block, which ck_item_pair forbids on purpose. See
-- docs/V2_PLAN.md 1.1 row 14.
--
-- Most movements need no row here.
CREATE TABLE content_set (
  content_id BIGINT  NOT NULL REFERENCES content(id) ON DELETE CASCADE,
  set_index  INTEGER NOT NULL,
  rep_index  INTEGER NOT NULL DEFAULT 0,
  reps       INTEGER,
  weight_kg  NUMERIC(6,2),
  seconds    INTEGER,
  PRIMARY KEY (content_id, set_index, rep_index),
  CONSTRAINT ck_content_set_index CHECK (set_index >= 1),
  CONSTRAINT ck_content_rep_index CHECK (rep_index >= 0)
);
-- A ladder lives here too: rungs of 3, 6 and 9 seconds are three rows, not the string
-- "3,6,9" in a column. That way the target and what you actually did are the same shape,
-- so the log can compare them without the app parsing anything.
--
-- rep_index is why the key has three columns. A ladder's rungs are REPS INSIDE ONE SET,
-- not sets, so (item, set) alone cannot hold them. An ordinary set is rep_index 0; a
-- three-rung ladder is set 1 with rep_index 1, 2, 3. This is in migration 001 because
-- SQLite cannot alter a primary key afterwards.

CREATE TABLE content_media (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content_id BIGINT       NOT NULL REFERENCES content(id) ON DELETE CASCADE,
  url        VARCHAR(512) NOT NULL,
  thumb_url  VARCHAR(512) NOT NULL DEFAULT '',
  position   INTEGER      NOT NULL DEFAULT 0
);
CREATE INDEX ix_media_content ON content_media (content_id);

CREATE TABLE tag (
  id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug VARCHAR(64) NOT NULL,
  name VARCHAR(64) NOT NULL,
  CONSTRAINT ux_tag_slug UNIQUE (slug)
);

CREATE TABLE content_tag (
  content_id BIGINT NOT NULL REFERENCES content(id) ON DELETE CASCADE,
  tag_id     BIGINT NOT NULL REFERENCES tag(id)     ON DELETE CASCADE,
  PRIMARY KEY (content_id, tag_id)
);
CREATE INDEX ix_content_tag_tag ON content_tag (tag_id);


-- ===========================================================================
-- PLANNING
-- ===========================================================================

CREATE TABLE plan (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id BIGINT       NOT NULL REFERENCES account(id) ON DELETE CASCADE,
  name       VARCHAR(255) NOT NULL,
  starts_on  VARCHAR(10)  NOT NULL,
  weeks      INTEGER      NOT NULL,
  goal       VARCHAR(255) NOT NULL DEFAULT '',
  focus      VARCHAR(32)  NOT NULL DEFAULT '',
  notes      TEXT         NOT NULL DEFAULT '',
  goals_json TEXT         NOT NULL DEFAULT '[]',
  created_at TIMESTAMP    NOT NULL,
  updated_at TIMESTAMP    NOT NULL,
  CONSTRAINT ck_plan_weeks CHECK (weeks >= 1)
);
CREATE INDEX ix_plan_account ON plan (account_id);
-- goals_json holds the before/after/how goals. They are only ever read and written with
-- the plan, never queried across plans, so they do not earn a table.

CREATE TABLE plan_slot (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plan_id      BIGINT      NOT NULL REFERENCES plan(id) ON DELETE CASCADE,
  session_id   BIGINT      NOT NULL,
  session_kind VARCHAR(16) NOT NULL DEFAULT 'session',
  weekday      INTEGER     NOT NULL,
  week         INTEGER     NOT NULL DEFAULT 0,
  CONSTRAINT fk_slot_session FOREIGN KEY (session_id, session_kind)
    REFERENCES content (id, kind) ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT ck_slot_session_kind CHECK (session_kind = 'session'),
  CONSTRAINT ck_slot_weekday CHECK (weekday BETWEEN 1 AND 7),
  CONSTRAINT ck_slot_week    CHECK (week >= 0),
  CONSTRAINT ux_slot UNIQUE (plan_id, week, weekday, session_id)
);
-- week 0 means every week. Not NULL: a nullable column in a unique key is not enforced,
-- because NULLs compare distinct.

-- What a cycle asks of one exercise. This is the Exercise targets page.
CREATE TABLE plan_target (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plan_id       BIGINT      NOT NULL REFERENCES plan(id) ON DELETE CASCADE,
  movement_id   BIGINT      NOT NULL,
  movement_kind VARCHAR(16) NOT NULL DEFAULT 'movement',
  week          INTEGER     NOT NULL DEFAULT 0,
  sets          INTEGER,
  reps          INTEGER,
  weight_kg     NUMERIC(6,2),
  rep_seconds   INTEGER,
  CONSTRAINT fk_target_movement FOREIGN KEY (movement_id, movement_kind)
    REFERENCES content (id, kind) ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT ck_target_movement_kind CHECK (movement_kind = 'movement'),
  CONSTRAINT ck_target_week CHECK (week >= 0),
  CONSTRAINT ux_target UNIQUE (plan_id, movement_id, week)
);
-- week 0 is the whole cycle; 1..n is that week only.
--
-- "Varies by week" is NOT a stored flag. It is true when a week > 0 row exists for that
-- plan and movement. A flag could disagree with the rows; a derived answer cannot.
--
-- A target is per movement per plan, so one row covers that movement wherever it appears
-- in the cycle. That is the intent of the page: "this cycle asks 5x5 of weighted
-- pull-ups", not "5x5 in Tuesday's session only".

CREATE TABLE scheduled (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id   BIGINT      NOT NULL REFERENCES account(id) ON DELETE CASCADE,
  plan_id      BIGINT      REFERENCES plan(id) ON DELETE CASCADE,
  session_id   BIGINT      NOT NULL,
  session_kind VARCHAR(16) NOT NULL DEFAULT 'session',
  on_date      VARCHAR(10) NOT NULL,
  position     INTEGER     NOT NULL DEFAULT 0,
  created_at   TIMESTAMP   NOT NULL,
  CONSTRAINT fk_sched_session FOREIGN KEY (session_id, session_kind)
    REFERENCES content (id, kind) ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT ck_sched_session_kind CHECK (session_kind = 'session')
);
CREATE INDEX ix_sched_account ON scheduled (account_id, on_date);
CREATE INDEX ix_sched_plan    ON scheduled (plan_id);
-- plan_id is nullable because a session can be scheduled by hand with no cycle behind it.
-- No natural key is possible as a result: the same session twice on one day is legal, and
-- position tells them apart. Duplicate prevention is the app's job, not a constraint's.

CREATE TABLE calendar_event (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id BIGINT       NOT NULL REFERENCES account(id) ON DELETE CASCADE,
  plan_id    BIGINT       REFERENCES plan(id) ON DELETE CASCADE,
  title      VARCHAR(128) NOT NULL,
  kind       VARCHAR(32)  NOT NULL,
  from_date  VARCHAR(10)  NOT NULL,
  to_date    VARCHAR(10)  NOT NULL,
  blocks     BOOLEAN      NOT NULL DEFAULT TRUE,
  notes      TEXT         NOT NULL DEFAULT '',
  CONSTRAINT ck_event_kind  CHECK (kind IN ('trip','injury','rest','competition','other')),
  CONSTRAINT ck_event_range CHECK (to_date >= from_date)
);
CREATE INDEX ix_event_account ON calendar_event (account_id, from_date);


-- ===========================================================================
-- PLACES
-- ===========================================================================

CREATE TABLE place (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id BIGINT       NOT NULL REFERENCES account(id) ON DELETE CASCADE,
  kind       VARCHAR(16)  NOT NULL,
  name       VARCHAR(128) NOT NULL,
  location   VARCHAR(128) NOT NULL DEFAULT '',
  board_type VARCHAR(32)  NOT NULL DEFAULT '',
  CONSTRAINT ck_place_kind CHECK (kind IN ('gym','crag','board'))
);
CREATE INDEX ix_place_account ON place (account_id);


-- ===========================================================================
-- THE LOG  --  frozen. reads no content table, ever.
-- ===========================================================================
--
-- UUID keys, because a phone with no signal creates these rows.
-- updated_at on all four, because sync has to know what changed.
--
-- Every name shown here is this table's own copy. Drop every content table and the whole
-- of history still renders. That is the rule, and place_name is part of it: reading the
-- venue name live would mean renaming a gym rewrites your history.

CREATE TABLE log (
  id           CHAR(36)     PRIMARY KEY,
  account_id   BIGINT       NOT NULL REFERENCES account(id) ON DELETE CASCADE,
  on_date      VARCHAR(10)  NOT NULL,

  scheduled_id BIGINT       REFERENCES scheduled(id) ON DELETE SET NULL,
  session_id   BIGINT       REFERENCES content(id)   ON DELETE SET NULL,
  session_slug VARCHAR(128) NOT NULL DEFAULT '',
  session_name VARCHAR(255) NOT NULL DEFAULT '',
  color        VARCHAR(16)  NOT NULL DEFAULT '',

  place_id     BIGINT       REFERENCES place(id) ON DELETE SET NULL,
  place_name   VARCHAR(128) NOT NULL DEFAULT '',
  place_kind   VARCHAR(16)  NOT NULL DEFAULT '',

  state        VARCHAR(16)  NOT NULL,
  started_at   TIMESTAMP,
  ended_at     TIMESTAMP,

  sleep        INTEGER,
  energy       INTEGER,
  rpe          INTEGER,
  focus        VARCHAR(32)  NOT NULL DEFAULT '',
  setting      VARCHAR(16)  NOT NULL DEFAULT '',

  went_well    TEXT         NOT NULL DEFAULT '',
  next_focus   TEXT         NOT NULL DEFAULT '',
  notes        TEXT         NOT NULL DEFAULT '',

  created_at   TIMESTAMP    NOT NULL,
  updated_at   TIMESTAMP    NOT NULL,

  CONSTRAINT ck_log_state CHECK (state IN ('draft','active','done','abandoned')),

  -- The target of log_entry's composite foreign key. Redundant as a key, and it is what
  -- makes the frozen account_id and on_date on a child structurally unable to diverge.
  CONSTRAINT ux_log_identity UNIQUE (id, account_id, on_date)
);
CREATE INDEX ix_log_account ON log (account_id, on_date);
CREATE INDEX ix_log_session ON log (session_id);
CREATE INDEX ix_log_sync    ON log (account_id, updated_at);
CREATE INDEX ix_log_state   ON log (account_id, state);
-- draft is a manual entry still being typed in. Hidden from history until saved.
-- A log with no entries is a journal entry. Not a second table.

CREATE TABLE log_entry (
  id            CHAR(36)     PRIMARY KEY,
  log_id        CHAR(36)     NOT NULL,

  -- Frozen from the parent so the progression query is answered by one index without
  -- joining log. ON UPDATE CASCADE on the composite key below is what keeps them in step.
  account_id    BIGINT       NOT NULL,
  on_date       VARCHAR(10)  NOT NULL,

  position      INTEGER      NOT NULL,
  block_name    VARCHAR(255) NOT NULL DEFAULT '',
  block_kind    VARCHAR(16)  NOT NULL DEFAULT '',

  -- The only link back to the movement, and it replaces the previous pair of movement_id
  -- (a row pointer, nulled on delete) and movement_slug (text). No foreign key: the log is
  -- frozen and must survive its content row being deleted outright, and a fork shares this
  -- value so it could not be a key to one row anyway.
  movement_key  CHAR(36)     NOT NULL,
  movement_name VARCHAR(255) NOT NULL,
  movement_kind VARCHAR(32)  NOT NULL DEFAULT '',

  -- what was asked of you that day
  t_sets        INTEGER,
  t_reps        INTEGER,
  t_weight_kg   NUMERIC(6,2),
  t_rep_seconds      INTEGER,
  t_rep_rest_seconds INTEGER,
  t_set_rest_seconds INTEGER,
  t_prep_seconds     INTEGER,
  t_seconds          INTEGER,

  -- what happened
  state           VARCHAR(16) NOT NULL DEFAULT 'pending',
  elapsed_seconds INTEGER     NOT NULL DEFAULT 0,
  set_mode        VARCHAR(16) NOT NULL DEFAULT 'simple',
  climb_kind      VARCHAR(32) NOT NULL DEFAULT '',
  climb_subtype   VARCHAR(32) NOT NULL DEFAULT '',
  notes           TEXT        NOT NULL DEFAULT '',

  created_at    TIMESTAMP    NOT NULL,
  updated_at    TIMESTAMP    NOT NULL,

  CONSTRAINT fk_entry_log FOREIGN KEY (log_id, account_id, on_date)
    REFERENCES log (id, account_id, on_date) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT ck_entry_state    CHECK (state IN ('pending','done','skipped')),
  CONSTRAINT ck_entry_set_mode CHECK (set_mode IN ('simple','per_set'))
);
-- The progression query on the run screen -- "the last five times you did this" -- is
-- served whole by this one index.
CREATE INDEX ix_entry_progression ON log_entry (account_id, movement_key, on_date DESC);
CREATE INDEX ix_entry_log         ON log_entry (log_id, position);

-- Resolves a frozen log row back to the live movement, and the movement to its forks.
-- Not unique, for the reason on content.content_key.
CREATE INDEX ix_content_key       ON content (content_key);

-- One set: what was asked of it, and what you did. Both on the row, so an open session
-- with per-set planning needs nothing extra.
CREATE TABLE log_set (
  id              CHAR(36) PRIMARY KEY,
  log_entry_id    CHAR(36) NOT NULL REFERENCES log_entry(id) ON DELETE CASCADE,
  set_index       INTEGER  NOT NULL,
  rep_index       INTEGER  NOT NULL DEFAULT 0,
  target_reps     INTEGER,
  target_weight_kg NUMERIC(6,2),
  target_seconds  INTEGER,
  reps            INTEGER,
  weight_kg       NUMERIC(6,2),
  seconds         INTEGER,
  updated_at      TIMESTAMP NOT NULL,
  CONSTRAINT ck_log_set_index CHECK (set_index >= 1),
  CONSTRAINT ck_log_rep_index CHECK (rep_index >= 0),
  CONSTRAINT ux_log_set UNIQUE (log_entry_id, set_index, rep_index)
);

CREATE TABLE log_climb (
  id           CHAR(36)    PRIMARY KEY,
  log_entry_id CHAR(36)    NOT NULL REFERENCES log_entry(id) ON DELETE CASCADE,
  position     INTEGER     NOT NULL DEFAULT 0,
  kind         VARCHAR(16) NOT NULL,
  setting      VARCHAR(16) NOT NULL DEFAULT '',
  subtype      VARCHAR(32) NOT NULL DEFAULT '',
  grade        VARCHAR(32) NOT NULL DEFAULT '',
  grade_ordinal INTEGER,
  style        VARCHAR(32) NOT NULL DEFAULT '',
  rope_style   VARCHAR(32) NOT NULL DEFAULT '',
  attempts     INTEGER     NOT NULL DEFAULT 0,
  sent         BOOLEAN     NOT NULL DEFAULT FALSE,
  seconds      INTEGER     NOT NULL DEFAULT 0,
  stars        INTEGER     NOT NULL DEFAULT 0,
  focus        TEXT        NOT NULL DEFAULT '',
  thoughts     TEXT        NOT NULL DEFAULT '',
  updated_at   TIMESTAMP   NOT NULL,
  CONSTRAINT ck_climb_kind  CHECK (kind IN ('boulder','sport','trad')),
  CONSTRAINT ck_climb_stars CHECK (stars BETWEEN 0 AND 3)
);
CREATE INDEX ix_climb_entry ON log_climb (log_entry_id, position);
-- grade_ordinal is what makes a pyramid sortable. Nullable, because an ARC lap or a
-- traverse has no grade.
--
-- Climbing is the one kind with no per-set target. There is no "asked 4x3" for
-- bouldering. Its target is the whole step -- log_entry.t_seconds for time on the wall,
-- or t_reps for a problem count -- and these tick rows are the record of what happened.


-- ===========================================================================
-- WHERE A NUMBER COMES FROM
-- ===========================================================================
--
-- Starting a run, for one exercise in one block of one session, in a cycle.
-- First match wins. NULL at a level means "not set here" and falls through.
--
--   1. content_item_set        this set specifically, if the block plans per set
--   2. plan_target week = N    what this cycle asks in week N
--   3. plan_target week = 0    what this cycle asks throughout
--   4. content_item            what the block asks
--   5. content.d_*             the movement's default
--
-- Whatever wins is copied into log_entry.t_* (and log_set.target_*) at the moment the
-- run is created, and is never recomputed. History shows what was asked, forever.
--
-- Alongside it, and never stored as a target, the run screen shows what you last did:
--
--   SELECT e.on_date, e.t_reps, s.reps, s.weight_kg
--   FROM   log_entry e
--   LEFT JOIN log_set s ON s.log_entry_id = e.id
--   WHERE  e.account_id = :me AND e.movement_key = :key
--   ORDER BY e.on_date DESC
--   LIMIT  5;
--
-- Served by ix_entry_progression. Touches no content table and does not join log.


-- ===========================================================================
-- FORKING
-- ===========================================================================
--
-- Shipped content is immutable. Editing it copies it to you.
--
-- A fork copies the thing and its structure, and stops before the movements:
--
--   fork a session  ->  new session row, new block rows, new content_item edges.
--                       the edges still point at the SAME movement rows.
--   fork a block    ->  new block row and its edges. same movements.
--   fork a movement ->  one new row. media copied.
--
-- The copy INHERITS content_key and sets forked_from_id, and it takes a NEW slug.
--
-- This reverses the old rule, which was "the copy keeps the original slug". That rule
-- existed because log_entry.movement_slug used to be the only durable link from your
-- history back to a movement. content_key is that link now, so the slug is free.
--
-- Freeing it is also what makes a same-author fork possible at all. Forking a row from a
-- private tree produces a second row with the SAME author, and ux_content_mine is
-- UNIQUE (author_id, kind, slug) -- so a copy that kept the slug could never insert. Every
-- edit to any of the 123 private-tree rows would fail on it. A new slug avoids that with
-- no change to the index.
--
-- Consequence for the library: your fork and the row it came from now differ by slug, so
-- "show mine, hide the one it replaced" resolves through forked_from_id, NOT by matching
-- slugs. For a shipped fork the old code could lean on the shared slug. It no longer can.
--
-- Reset to default is deleting your copy. Anything pointing at it has to be repointed at
-- forked_from_id first -- which is why that column is not merely decorative.


-- ===========================================================================
-- WHAT GORM CANNOT EXPRESS
-- ===========================================================================
--
-- AutoMigrate handles the tables, columns, plain indexes, and the partial unique indexes
-- via `uniqueIndex:...,where:...` -- verified: the sqlite and postgres drivers both emit
-- the predicate. The following need explicit statements beside it, identical on both
-- engines:
--
--   1. The four composite foreign keys: content_item x2, plan_slot, plan_target,
--      scheduled, log_entry. GORM has no struct tag for a multi-column reference.
--   2. UNIQUE (id, kind) on content and UNIQUE (id, account_id, on_date) on log, since
--      they exist only to be foreign key targets.
--   3. ON UPDATE CASCADE on log_entry's parent key.
--
-- SQLite cannot add a CHECK to an existing table, so every CHECK above has to be present
-- when the table is first created. That makes the initial migration a create, never an
-- alter, and it means these statements run in order at first boot.
