name: CI

on:
  push:
  pull_request:

jobs:
  test:
    name: Vet and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31

      - name: Start postgres
        run: nix develop -c make db-up

      - name: Vet
        run: nix develop -c go vet ./...

      - name: Test
        run: nix develop -c go test ./...
