-- Generated from docs/SCHEMA_V2.sql. Do not edit by hand.
-- Regenerate with: make migrations
--
-- PostgreSQL. Identity columns are BIGINT GENERATED BY DEFAULT AS IDENTITY.

-- +goose Up

-- +goose StatementBegin
CREATE TABLE account (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email                VARCHAR(255) NOT NULL,
  password_hash        VARCHAR(255) NOT NULL,
  height_cm            INTEGER,
  ape_index_cm         INTEGER,
  boulder_grade_system VARCHAR(32)  NOT NULL DEFAULT 'font',
  route_grade_system   VARCHAR(32)  NOT NULL DEFAULT 'french',
  max_pull_ups         INTEGER,
  max_hang_kg          NUMERIC(5,2),
  time_zone            VARCHAR(64)  NOT NULL DEFAULT 'UTC',
  token_epoch          INTEGER      NOT NULL DEFAULT 0,
  created_at           TIMESTAMP    NOT NULL,
  updated_at           TIMESTAMP    NOT NULL,
  CONSTRAINT ux_account_email UNIQUE (email)
);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE TABLE body_measurement (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id BIGINT      NOT NULL REFERENCES account(id) ON DELETE CASCADE,
  taken_on   VARCHAR(10) NOT NULL,
  weight_kg  NUMERIC(5,2),
  CONSTRAINT ux_body_measurement UNIQUE (account_id, taken_on)
);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE TABLE grade_milestone (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id    BIGINT      NOT NULL REFERENCES account(id) ON DELETE CASCADE,
  taken_on      VARCHAR(10) NOT NULL,
  discipline    VARCHAR(16) NOT NULL,
  grade         VARCHAR(32) NOT NULL,
  grade_ordinal INTEGER     NOT NULL,
  CONSTRAINT ck_grade_discipline CHECK (discipline IN ('boulder','route')),
  CONSTRAINT ux_grade_milestone  UNIQUE (account_id, discipline, taken_on)
);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE TABLE content (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind           VARCHAR(16)  NOT NULL,
  slug           VARCHAR(128) NOT NULL,
  name           VARCHAR(255) NOT NULL,
  content_key    CHAR(36)     NOT NULL,
  source_tree    VARCHAR(64),
  author_id      BIGINT       REFERENCES account(id) ON DELETE CASCADE,
  forked_from_id BIGINT,
  notes          TEXT         NOT NULL DEFAULT '',
  source         VARCHAR(64)  NOT NULL DEFAULT '',
  retired_on     VARCHAR(10),
  movement_kind  VARCHAR(32),
  per_side       BOOLEAN      NOT NULL DEFAULT FALSE,
  d_sets         INTEGER,
  d_reps         INTEGER,
  d_weight_kg    NUMERIC(6,2),
  d_rep_seconds      INTEGER,
  d_rep_rest_seconds INTEGER,
  d_set_rest_seconds INTEGER,
  d_prep_seconds     INTEGER,
  d_seconds          INTEGER,
  block_kind     VARCHAR(16),
  pick_count     INTEGER,
  color          VARCHAR(16)  NOT NULL DEFAULT '',
  needs          VARCHAR(255) NOT NULL DEFAULT '',
  created_at     TIMESTAMP    NOT NULL,
  updated_at     TIMESTAMP    NOT NULL,
  CONSTRAINT ck_content_kind       CHECK (kind IN ('movement','menu','block','session')),
  CONSTRAINT ck_content_block_kind CHECK (block_kind IS NULL
                                          OR block_kind IN ('warmup','main','cooldown')),
  CONSTRAINT ck_content_pick       CHECK (pick_count IS NULL OR pick_count >= 1),
  CONSTRAINT ck_content_not_self   CHECK (forked_from_id IS NULL OR forked_from_id <> id),
  CONSTRAINT fk_content_forked FOREIGN KEY (forked_from_id, kind)
    REFERENCES content (id, kind) ON DELETE RESTRICT,
  CONSTRAINT ux_content_id_kind    UNIQUE (id, kind)
);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE UNIQUE INDEX ux_content_shipped ON content (kind, slug)            WHERE author_id IS NULL;
-- +goose StatementEnd

-- +goose StatementBegin
CREATE UNIQUE INDEX ux_content_mine    ON content (author_id, kind, slug) WHERE author_id IS NOT NULL;
-- +goose StatementEnd

-- +goose StatementBegin
CREATE INDEX ix_content_author ON content (author_id);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE INDEX ix_content_kind   ON content (kind);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE INDEX ix_content_forked ON content (forked_from_id);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE INDEX ix_content_list   ON content (author_id, kind, name);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE TABLE content_item (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id        BIGINT      NOT NULL,
  parent_kind      VARCHAR(16) NOT NULL,
  child_id         BIGINT      NOT NULL,
  child_kind       VARCHAR(16) NOT NULL,
  position         INTEGER     NOT NULL,
  sets             INTEGER,
  reps             INTEGER,
  weight_kg        NUMERIC(6,2),
  rep_seconds      INTEGER,
  rep_rest_seconds INTEGER,
  set_rest_seconds INTEGER,
  prep_seconds     INTEGER,
  seconds          INTEGER,
  notes            TEXT        NOT NULL DEFAULT '',
  CONSTRAINT fk_item_parent FOREIGN KEY (parent_id, parent_kind)
    REFERENCES content (id, kind) ON DELETE CASCADE,
  CONSTRAINT fk_item_child  FOREIGN KEY (child_id, child_kind)
    REFERENCES content (id, kind) ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT ck_item_pair CHECK (
       (parent_kind = 'session' AND child_kind = 'block')
    OR (parent_kind = 'block'   AND child_kind IN ('movement','menu'))
    OR (parent_kind = 'menu'    AND child_kind = 'movement')
  ),
  CONSTRAINT ck_item_not_self CHECK (parent_id <> child_id),
  CONSTRAINT ux_item_edge UNIQUE (parent_id, child_id)
);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE INDEX ix_item_parent ON content_item (parent_id, position);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE INDEX ix_item_child  ON content_item (child_id);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE TABLE content_item_set (
  content_item_id BIGINT  NOT NULL REFERENCES content_item(id) ON DELETE CASCADE,
  set_index       INTEGER NOT NULL,
  rep_index       INTEGER NOT NULL DEFAULT 0,
  reps            INTEGER,
  weight_kg       NUMERIC(6,2),
  seconds         INTEGER,
  PRIMARY KEY (content_item_id, set_index, rep_index),
  CONSTRAINT ck_set_index CHECK (set_index >= 1),
  CONSTRAINT ck_rep_index CHECK (rep_index >= 0)
);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE TABLE content_set (
  content_id BIGINT  NOT NULL REFERENCES content(id) ON DELETE CASCADE,
  set_index  INTEGER NOT NULL,
  rep_index  INTEGER NOT NULL DEFAULT 0,
  reps       INTEGER,
  weight_kg  NUMERIC(6,2),
  seconds    INTEGER,
  PRIMARY KEY (content_id, set_index, rep_index),
  CONSTRAINT ck_content_set_index CHECK (set_index >= 1),
  CONSTRAINT ck_content_rep_index CHECK (rep_index >= 0)
);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE TABLE content_media (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content_id BIGINT       NOT NULL REFERENCES content(id) ON DELETE CASCADE,
  url        VARCHAR(512) NOT NULL,
  thumb_url  VARCHAR(512) NOT NULL DEFAULT '',
  position   INTEGER      NOT NULL DEFAULT 0
);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE INDEX ix_media_content ON content_media (content_id);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE TABLE tag (
  id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug VARCHAR(64) NOT NULL,
  name VARCHAR(64) NOT NULL,
  CONSTRAINT ux_tag_slug UNIQUE (slug)
);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE TABLE content_tag (
  content_id BIGINT NOT NULL REFERENCES content(id) ON DELETE CASCADE,
  tag_id     BIGINT NOT NULL REFERENCES tag(id)     ON DELETE CASCADE,
  PRIMARY KEY (content_id, tag_id)
);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE INDEX ix_content_tag_tag ON content_tag (tag_id);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE TABLE plan (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id BIGINT       NOT NULL REFERENCES account(id) ON DELETE CASCADE,
  name       VARCHAR(255) NOT NULL,
  starts_on  VARCHAR(10)  NOT NULL,
  weeks      INTEGER      NOT NULL,
  goal       VARCHAR(255) NOT NULL DEFAULT '',
  focus      VARCHAR(32)  NOT NULL DEFAULT '',
  notes      TEXT         NOT NULL DEFAULT '',
  goals_json TEXT         NOT NULL DEFAULT '[]',
  created_at TIMESTAMP    NOT NULL,
  updated_at TIMESTAMP    NOT NULL,
  CONSTRAINT ck_plan_weeks CHECK (weeks >= 1)
);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE INDEX ix_plan_account ON plan (account_id);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE TABLE plan_slot (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plan_id      BIGINT      NOT NULL REFERENCES plan(id) ON DELETE CASCADE,
  session_id   BIGINT      NOT NULL,
  session_kind VARCHAR(16) NOT NULL DEFAULT 'session',
  weekday      INTEGER     NOT NULL,
  week         INTEGER     NOT NULL DEFAULT 0,
  CONSTRAINT fk_slot_session FOREIGN KEY (session_id, session_kind)
    REFERENCES content (id, kind) ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT ck_slot_session_kind CHECK (session_kind = 'session'),
  CONSTRAINT ck_slot_weekday CHECK (weekday BETWEEN 1 AND 7),
  CONSTRAINT ck_slot_week    CHECK (week >= 0),
  CONSTRAINT ux_slot UNIQUE (plan_id, week, weekday, session_id)
);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE TABLE plan_target (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plan_id       BIGINT      NOT NULL REFERENCES plan(id) ON DELETE CASCADE,
  movement_id   BIGINT      NOT NULL,
  movement_kind VARCHAR(16) NOT NULL DEFAULT 'movement',
  week          INTEGER     NOT NULL DEFAULT 0,
  sets          INTEGER,
  reps          INTEGER,
  weight_kg     NUMERIC(6,2),
  rep_seconds   INTEGER,
  CONSTRAINT fk_target_movement FOREIGN KEY (movement_id, movement_kind)
    REFERENCES content (id, kind) ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT ck_target_movement_kind CHECK (movement_kind = 'movement'),
  CONSTRAINT ck_target_week CHECK (week >= 0),
  CONSTRAINT ux_target UNIQUE (plan_id, movement_id, week)
);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE TABLE scheduled (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id   BIGINT      NOT NULL REFERENCES account(id) ON DELETE CASCADE,
  plan_id      BIGINT      REFERENCES plan(id) ON DELETE CASCADE,
  session_id   BIGINT      NOT NULL,
  session_kind VARCHAR(16) NOT NULL DEFAULT 'session',
  on_date      VARCHAR(10) NOT NULL,
  position     INTEGER     NOT NULL DEFAULT 0,
  created_at   TIMESTAMP   NOT NULL,
  CONSTRAINT fk_sched_session FOREIGN KEY (session_id, session_kind)
    REFERENCES content (id, kind) ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT ck_sched_session_kind CHECK (session_kind = 'session')
);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE INDEX ix_sched_account ON scheduled (account_id, on_date);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE INDEX ix_sched_plan    ON scheduled (plan_id);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE TABLE calendar_event (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id BIGINT       NOT NULL REFERENCES account(id) ON DELETE CASCADE,
  plan_id    BIGINT       REFERENCES plan(id) ON DELETE CASCADE,
  title      VARCHAR(128) NOT NULL,
  kind       VARCHAR(32)  NOT NULL,
  from_date  VARCHAR(10)  NOT NULL,
  to_date    VARCHAR(10)  NOT NULL,
  blocks     BOOLEAN      NOT NULL DEFAULT TRUE,
  notes      TEXT         NOT NULL DEFAULT '',
  CONSTRAINT ck_event_kind  CHECK (kind IN ('trip','injury','rest','competition','other')),
  CONSTRAINT ck_event_range CHECK (to_date >= from_date)
);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE INDEX ix_event_account ON calendar_event (account_id, from_date);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE TABLE place (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id BIGINT       NOT NULL REFERENCES account(id) ON DELETE CASCADE,
  kind       VARCHAR(16)  NOT NULL,
  name       VARCHAR(128) NOT NULL,
  location   VARCHAR(128) NOT NULL DEFAULT '',
  board_type VARCHAR(32)  NOT NULL DEFAULT '',
  CONSTRAINT ck_place_kind CHECK (kind IN ('gym','crag','board'))
);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE INDEX ix_place_account ON place (account_id);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE TABLE log (
  id           CHAR(36)     PRIMARY KEY,
  account_id   BIGINT       NOT NULL REFERENCES account(id) ON DELETE CASCADE,
  on_date      VARCHAR(10)  NOT NULL,
  scheduled_id BIGINT       REFERENCES scheduled(id) ON DELETE SET NULL,
  session_id   BIGINT       REFERENCES content(id)   ON DELETE SET NULL,
  session_slug VARCHAR(128) NOT NULL DEFAULT '',
  session_name VARCHAR(255) NOT NULL DEFAULT '',
  color        VARCHAR(16)  NOT NULL DEFAULT '',
  place_id     BIGINT       REFERENCES place(id) ON DELETE SET NULL,
  place_name   VARCHAR(128) NOT NULL DEFAULT '',
  place_kind   VARCHAR(16)  NOT NULL DEFAULT '',
  state        VARCHAR(16)  NOT NULL,
  started_at   TIMESTAMP,
  ended_at     TIMESTAMP,
  sleep        INTEGER,
  energy       INTEGER,
  rpe          INTEGER,
  focus        VARCHAR(32)  NOT NULL DEFAULT '',
  setting      VARCHAR(16)  NOT NULL DEFAULT '',
  went_well    TEXT         NOT NULL DEFAULT '',
  next_focus   TEXT         NOT NULL DEFAULT '',
  notes        TEXT         NOT NULL DEFAULT '',
  created_at   TIMESTAMP    NOT NULL,
  updated_at   TIMESTAMP    NOT NULL,
  CONSTRAINT ck_log_state CHECK (state IN ('draft','active','done','abandoned')),
  CONSTRAINT ux_log_identity UNIQUE (id, account_id, on_date)
);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE INDEX ix_log_account ON log (account_id, on_date);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE INDEX ix_log_session ON log (session_id);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE INDEX ix_log_sync    ON log (account_id, updated_at);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE INDEX ix_log_state   ON log (account_id, state);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE TABLE log_entry (
  id            CHAR(36)     PRIMARY KEY,
  log_id        CHAR(36)     NOT NULL,
  account_id    BIGINT       NOT NULL,
  on_date       VARCHAR(10)  NOT NULL,
  position      INTEGER      NOT NULL,
  block_name    VARCHAR(255) NOT NULL DEFAULT '',
  block_kind    VARCHAR(16)  NOT NULL DEFAULT '',
  movement_key  CHAR(36)     NOT NULL,
  movement_name VARCHAR(255) NOT NULL,
  movement_kind VARCHAR(32)  NOT NULL DEFAULT '',
  t_sets        INTEGER,
  t_reps        INTEGER,
  t_weight_kg   NUMERIC(6,2),
  t_rep_seconds      INTEGER,
  t_rep_rest_seconds INTEGER,
  t_set_rest_seconds INTEGER,
  t_prep_seconds     INTEGER,
  t_seconds          INTEGER,
  state           VARCHAR(16) NOT NULL DEFAULT 'pending',
  elapsed_seconds INTEGER     NOT NULL DEFAULT 0,
  set_mode        VARCHAR(16) NOT NULL DEFAULT 'simple',
  climb_kind      VARCHAR(32) NOT NULL DEFAULT '',
  climb_subtype   VARCHAR(32) NOT NULL DEFAULT '',
  notes           TEXT        NOT NULL DEFAULT '',
  created_at    TIMESTAMP    NOT NULL,
  updated_at    TIMESTAMP    NOT NULL,
  CONSTRAINT fk_entry_log FOREIGN KEY (log_id, account_id, on_date)
    REFERENCES log (id, account_id, on_date) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT ck_entry_state    CHECK (state IN ('pending','done','skipped')),
  CONSTRAINT ck_entry_set_mode CHECK (set_mode IN ('simple','per_set'))
);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE INDEX ix_entry_progression ON log_entry (account_id, movement_key, on_date DESC);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE INDEX ix_entry_log         ON log_entry (log_id, position);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE INDEX ix_content_key       ON content (content_key);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE TABLE log_set (
  id              CHAR(36) PRIMARY KEY,
  log_entry_id    CHAR(36) NOT NULL REFERENCES log_entry(id) ON DELETE CASCADE,
  set_index       INTEGER  NOT NULL,
  rep_index       INTEGER  NOT NULL DEFAULT 0,
  target_reps     INTEGER,
  target_weight_kg NUMERIC(6,2),
  target_seconds  INTEGER,
  reps            INTEGER,
  weight_kg       NUMERIC(6,2),
  seconds         INTEGER,
  updated_at      TIMESTAMP NOT NULL,
  CONSTRAINT ck_log_set_index CHECK (set_index >= 1),
  CONSTRAINT ck_log_rep_index CHECK (rep_index >= 0),
  CONSTRAINT ux_log_set UNIQUE (log_entry_id, set_index, rep_index)
);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE TABLE log_climb (
  id           CHAR(36)    PRIMARY KEY,
  log_entry_id CHAR(36)    NOT NULL REFERENCES log_entry(id) ON DELETE CASCADE,
  position     INTEGER     NOT NULL DEFAULT 0,
  kind         VARCHAR(16) NOT NULL,
  setting      VARCHAR(16) NOT NULL DEFAULT '',
  subtype      VARCHAR(32) NOT NULL DEFAULT '',
  grade        VARCHAR(32) NOT NULL DEFAULT '',
  grade_ordinal INTEGER,
  style        VARCHAR(32) NOT NULL DEFAULT '',
  rope_style   VARCHAR(32) NOT NULL DEFAULT '',
  attempts     INTEGER     NOT NULL DEFAULT 0,
  sent         BOOLEAN     NOT NULL DEFAULT FALSE,
  seconds      INTEGER     NOT NULL DEFAULT 0,
  stars        INTEGER     NOT NULL DEFAULT 0,
  focus        TEXT        NOT NULL DEFAULT '',
  thoughts     TEXT        NOT NULL DEFAULT '',
  updated_at   TIMESTAMP   NOT NULL,
  CONSTRAINT ck_climb_kind  CHECK (kind IN ('boulder','sport','trad')),
  CONSTRAINT ck_climb_stars CHECK (stars BETWEEN 0 AND 3)
);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE INDEX ix_climb_entry ON log_climb (log_entry_id, position);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
-- Refused on purpose. Migrations are append-only after the first boot, and
-- SQLite can neither drop a CHECK nor alter a primary key, so a down migration
-- cannot honestly reverse 00001.
SELECT 1;
-- +goose StatementEnd
